task_name: template
render_freq: 0       # render frequence (0: render off)
use_seed: False          # use seed ,if value is True, the seed file has existed in ./seeds/{task_name}.txt  
collect_data: True  # collect data
save_path: './data'
dual_arm: True
st_episode: 0    # begin_episode 
camera_w: 640       #
camera_h: 480       # camera args
pcd_crop: True      #...  
pcd_down_sample_num: 1024    # pcd down sample num
episode_num: 100    # episode num
save_type:
  raw_data: False
  pkl: True
data_type:          # the data types should be saved
  rgb: False
  observer : False
  depth: False
  pointcloud: True
  conbine: False
  endpose: True
  qpos: True
  mesh_segmentation: False
  actor_segmentation: False
