task_name: block_hammer_beat
render_freq: 0
use_seed: false
collect_data: true
save_path: ./data
dual_arm: true
st_episode: 0
camera_w: 320
camera_h: 240
pcd_crop: true
pcd_down_sample_num: 1024
pose_type: gt
episode_num: 1
save_type:
  raw_data: True
  pkl: False
data_type:
  rgb: True
  observer: false
  depth: false
  pointcloud: False
  conbine: false
  endpose: False
  qpos: true
  mesh_segmentation: false
  actor_segmentation: false
