task_name: hammer_beat
render_freq: 0       # render frequence (0: render off)
use_seed: True          # use seed ,if value is True, the seed file has existed in ./seeds/{task_name}.txt  
collect_data: True  # collect data
save_path: './data'
st_episode: 0    # begin_episode 
camera_w: 640       #
camera_h: 480       # camera args
pcd_crop: False      #...  
pcd_down_sample_num: 0    # pcd down sample num 
dual_arm: False
pose_type: "gt"
episode_num: 50    # episode num
save_type:
  raw_data: True
  pkl: False
data_type:          # the data types should be saved
  rgb: True
  expert : False
  depth: True
  pointcloud: False
  conbine: False
  endpose: True
  qpos: True
  mesh_segmentation: True
  actor_segmentation: True