task_name: move_brush
render_freq: 0       # render frequence (0: render off)
use_seed: False          # use seed ,if value is True, the seed file has existed in ./seeds/{task_name}.txt  
collect_data: True  # collect data
# save_path: './benchmark_data/'
save_path: './move_brush_0804_20'
st_episode: 0    # begin_episode 
camera_w: 336       #
camera_h: 224       # camera args
pcd_crop: True      #...  
pcd_down_sample_num: 1024    # pcd down sample num 
episode_num: 50    # episode num
data_type:          # the data types should be saved
  rgb: False
  depth: False
  point_cloud: False
  end_pose: False     
  qpos: False
  mesh_segmentation: True
  actor_segmentation: True
