task_name: mug_hanging
render_freq: 0
use_seed: false
collect_data: true
save_path: ./data
dual_arm: true
st_episode: 0
camera_w: 336
camera_h: 224
pcd_crop: true
pcd_down_sample_num: 1024
pose_type: gt
episode_num: 50
save_type:
  raw_data: false
  pkl: true
data_type:
  rgb: true
  observer: false
  depth: false
  pointcloud: false
  conbine: false
  endpose: true
  qpos: true
  mesh_segmentation: false
  actor_segmentation: false
