task_name: pick_empty_cup
render_freq: 10       # render frequence (0: render off)
use_seed: False          # use seed ,if value is True, the seed file has existed in ./seeds/{task_name}.txt  
collect_data: False  # collect data
save_path: './data'
st_episode: 0    # begin_episode 
camera_w: 640       #
camera_h: 480       # camera args
pcd_crop: True      #...  
pcd_down_sample_num: 1024    # pcd down sample num 
dual_arm: True
pose_type: "gt"
episode_num: 10    # episode num
save_type:
  raw_data: True
  pkl: False
data_type:          # the data types should be saved
  rgb: True
  expert : True
  depth: False
  pointcloud: False
  endpose: False
  qpos: False
  mesh_segmentation: False
  actor_segmentation: False
