task_name: put_ball_into_dustpan
render_freq: 0       # render frequence (0: render off)
use_seed: True          # use seed ,if value is True, the seed file has existed in ./seeds/{task_name}.txt  
collect_data: True  # collect data
save_path: './data'
st_episode: 1    # begin_episode 
camera_w: 640       #
camera_h: 480       # camera args
pcd_crop: True      #...  
pcd_down_sample_num: 4096    # pcd down sample num 
dual_arm: True
pose_type: "gt"
episode_num: 50    # episode num
save_type:
  raw_data: True
  pkl: False
data_type:          # the data types should be saved
  rgb: True
  observer : False
  depth: False
  pointcloud: True
  endpose: False
  qpos: False
  mesh_segmentation: False
  actor_segmentation: False

