task_name: put_block_into_dustpan
render_freq: 0       # render frequence (0: render off)
use_seed: True          # use seed ,if value is True, the seed file has existed in ./seeds/{task_name}.txt  
collect_data: True  # collect data
save_path: './data'
dual_arm: True
st_episode: 0    # begin_episode 
camera_w: 336       #
camera_h: 224       # camera args
pcd_crop: True      #...  
pcd_down_sample_num: 1024    # pcd down sample num 
pose_type: "gt"
episode_num: 50    # episode num
save_type:
  raw_data: False
  pkl: True
data_type:          # the data types should be saved
  rgb: True
  observer : False
  depth: True
  pointcloud: True
  conbine: True
  endpose: True
  qpos: True
  mesh_segmentation: False
  actor_segmentation: False
